# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Which Environment do you want to create DEV/QAS'
        # Default value if no value is explicitly provided
        default: 'DEV'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  AzureLogin:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      PREFIX: "Dev"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    - name: Set Resource Group name
      run: |
          rgname=${{ github.event.inputs.name }}Auto$(echo ${ GITHUB_REF } | sed 's/[^a-z]//g')
          echo PREFIX=${rgname} >> env.PREFIX
    - name: Create Resource Group
      uses: azure/CLI@v1
      with:
          inlineScript: |
            az group create --name ${PREFIX} --location japaneast
      
